services:
  thermal-img-experiment:
    image: mamonet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/modelos
    container_name: experimento-redes-neurais
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

