services:
  thermal-img-experiment:
    image: mamonet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/experiment/output
    container_name: meu_container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

